import React from 'react';
import {
  View,
  Text,
  ScrollView,
  TouchableOpacity,
  Share,
  Alert,
} from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';

const SummaryScreen = ({ route, navigation }) => {
  const { summaryData } = route.params || {};

  // Fallback data for demo purposes
  const data = summaryData || {
    title: "Sample Meeting Summary",
    summary: "This is a sample summary that would be generated by the AI. It includes key points, action items, and important decisions made during the meeting or from the notes provided.",
    tags: ["meeting", "project", "deadline", "team"],
    sentiment: "neutral"
  };

  const getSentimentColor = (sentiment) => {
    switch (sentiment?.toLowerCase()) {
      case 'positive':
        return 'text-green-600 bg-green-100';
      case 'negative':
        return 'text-red-600 bg-red-100';
      default:
        return 'text-blue-600 bg-blue-100';
    }
  };

  const getSentimentEmoji = (sentiment) => {
    switch (sentiment?.toLowerCase()) {
      case 'positive':
        return '😊';
      case 'negative':
        return '😔';
      default:
        return '😐';
    }
  };

  const handleShare = async () => {
    try {
      const shareContent = `${data.title}\n\n${data.summary}\n\nTags: ${data.tags?.join(', ')}\nMood: ${data.sentiment}`;
      
      await Share.share({
        message: shareContent,
        title: data.title,
      });
    } catch (error) {
      Alert.alert('Error', 'Failed to share summary');
    }
  };

  const handleNewNote = () => {
    navigation.navigate('NoteInput');
  };

  return (
    <SafeAreaView className="flex-1 bg-gray-50">
      <ScrollView className="flex-1 px-4 pt-4">
        {/* Title Section */}
        <View className="mb-6">
          <Text className="text-3xl font-bold text-gray-900 mb-2 leading-tight">
            {data.title}
          </Text>
          
          {/* Sentiment Badge */}
          <View className="flex-row items-center mb-4">
            <View className={`px-3 py-2 rounded-full flex-row items-center ${getSentimentColor(data.sentiment)}`}>
              <Text className="text-lg mr-1">
                {getSentimentEmoji(data.sentiment)}
              </Text>
              <Text className={`font-medium text-sm ${getSentimentColor(data.sentiment).split(' ')[0]}`}>
                Mood: {data.sentiment}
              </Text>
            </View>
          </View>
        </View>

        {/* Summary Section */}
        <View className="mb-6">
          <Text className="text-lg font-semibold text-gray-900 mb-3">
            📄 Summary
          </Text>
          <View className="bg-white rounded-xl p-4 shadow-sm border border-gray-200">
            <Text className="text-gray-800 text-base leading-relaxed">
              {data.summary}
            </Text>
          </View>
        </View>

        {/* Tags Section */}
        {data.tags && data.tags.length > 0 && (
          <View className="mb-6">
            <Text className="text-lg font-semibold text-gray-900 mb-3">
              🏷️ Tags
            </Text>
            <View className="flex-row flex-wrap">
              {data.tags.map((tag, index) => (
                <View
                  key={index}
                  className="bg-blue-100 px-3 py-2 rounded-full mr-2 mb-2"
                >
                  <Text className="text-blue-700 font-medium text-sm">
                    #{tag}
                  </Text>
                </View>
              ))}
            </View>
          </View>
        )}

        {/* Action Buttons */}
        <View className="mb-8 space-y-3">
          <TouchableOpacity
            onPress={handleShare}
            className="bg-green-500 py-4 rounded-xl flex-row justify-center items-center shadow-lg"
            style={{
              shadowColor: '#34C759',
              shadowOffset: { width: 0, height: 4 },
              shadowOpacity: 0.3,
              shadowRadius: 8,
              elevation: 8,
            }}
          >
            <Text className="text-white font-semibold text-lg">
              📤 Share Summary
            </Text>
          </TouchableOpacity>

          <TouchableOpacity
            onPress={handleNewNote}
            className="bg-blue-500 py-4 rounded-xl flex-row justify-center items-center shadow-lg"
            style={{
              shadowColor: '#007AFF',
              shadowOffset: { width: 0, height: 4 },
              shadowOpacity: 0.3,
              shadowRadius: 8,
              elevation: 8,
            }}
          >
            <Text className="text-white font-semibold text-lg">
              ✨ Create New Note
            </Text>
          </TouchableOpacity>
        </View>

        {/* Metadata */}
        <View className="bg-gray-100 rounded-xl p-4 mb-6">
          <Text className="text-gray-600 text-sm text-center">
            ✨ Powered by QuickNote AI
          </Text>
          <Text className="text-gray-500 text-xs text-center mt-1">
            Generated on {new Date().toLocaleDateString()}
          </Text>
        </View>
      </ScrollView>
    </SafeAreaView>
  );
};

export default SummaryScreen;

